# Generated by Django 5.0.6 on 2024-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
